### Request 1
GET http://localhost:8081/item
Content-type: application/json

### Request 2
GET http://localhost:8081/item/3
Content-type: application/json

### Request 3
GET http://localhost:8081/user_info
Content-type: application/json

### Request 4
POST http://localhost:8081/user_info
Content-type: application/json

{
  "first_name": "GI",
  "last_name": "JOE",
  "user_name": "GI JOE",
  "password": "YOJOE!"
}

### Request 5
POST http://localhost:8081/item
Content-type: application/json

{
  "user_id": "2",
  "item_name": "X-Wing",
  "description": "All around great starfighter",
  "quantity": "10"
}

### Request 6
PATCH http://localhost:8081/item/id
'Content-type': 'application/json; charset=UTF-8'
user_id: updateUserInfoID,
item_name: updateItemName,
description: updateDescription,
quantity: updateQuantity

### Request 7
DELETE http://localhost:8081/user_info/10
Content-type: application/json

### Request 8
DELETE http://localhost:8081/item/3
Content-type: application/json